# Generated by Django 5.2.1 on 2025-06-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tbl_Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("mobile_no", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "tbl_employee",
            },
        ),
    ]
